### ISSUE TITLE
Remove ssh-injection script, move to ansible config

### ISSUE THREAD

**Issue by DerekHarter** [DerekHarter/cloudstack#2]
We should be able to perform the injection of ansible management key from ansible, I discovered.  We can specify the username and password instead of using the default.  So do the following:

1. Add in variables for default user and password for initial access to `vars/globals.yml` file:
```
default_access_user: cloudstack
default_access_password: cloudstack
```
2. In deploy-cloudstack add in something like at top before doing anything else
```
- hosts: all
  vars_files:
    - vars/globals.yml
  roles:
    - ansiblesshmanagement
 ```
The intent is that all nodes in inventory need to be setup for ansible ssh management, so this will be done on all of them.
3. Create the role.  Should be able to use the `authorized_key` module as usual, but specify username, password.  Like this:
```
- name: Copy cloudstack management key from ansible manager buffer to the agent node
  authorized_key:
    user: cloudstack
    state: present
    key: "{{ lookup('file', 'keys/cloudstack.key.pub') }}"
  ansible_user: cloudstack
  ansible_password: cloudstack
```

The cloudstack user has sudo privileges.  The above example should add the manager key as an authorized key.  Once it is there, could then use sudo command to just copy it into the root authroized_host file.
